name: Inventory App PyPipeline
run-name: ${{ github.actor }} modified a python file.
on: [push]
jobs:
  Qualaity-Assurance:
    runs-on: ubuntu-latest
    steps:

      - name: Check out reository code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::606026656431:role/inventory-pipeline-role

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Lint Python files with ruff
        run: |
          ruff check *.py
